name: scientific-calculator
title: Scientific Calculator
version: '1.0.1' # Updated version
summary: Native lightweight scientific calculator desktop app
description: |
  A native scientific calculator featuring precision math evaluation,
  trigonometric functions, bracket parsing, and persistent history.

icon: snap/gui/icon.png

contact: https://github.com/Shahriyar-Rahim
website: https://github.com/Shahriyar-Rahim
license: ISC

grade: stable
confinement: strict
base: core22

apps:
  scientific-calculator:
    command: ScientificCalculator --no-sandbox
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback

parts:
  app:
    plugin: dump
    source: ./out/ScientificCalculator-linux-x64
    organize:
      '*': /